### ISSUE TITLE
No data for next year 

### ISSUE THREAD

**Issue by SirRene** [Johnwulp/rad-afval#1]
Hi,

Thanks for this great plugin. We use it daily.
But now it shows no data for next year. Could you please have a look at this issue?

Rgds,
René

**Comment by Johnwulp** [comment]
Hi Rene, on the site https://www.radhw.nl/inwoners/ophaalschema there is also no data for 2021 in my case. If you type in you’re postalcode, do you get response?

J

**Comment by SirRene** [comment]
Wow.. That's a quick response!
But you're right. No data for 2021.
Maybe it has something to do with the fact that the RAD has launched it's own app. So, maybe using another db?

**Comment by Johnwulp** [comment]
Yes could be! I’ll wait until next 2021, if there is no data I will try to find a new source. Thanks for reporting!

**Comment by martinprive** [comment]
First of all thank you for your work, works great in Home Assistant. I think i've found a new source: https://www.radbv.nl/afvalkalender/. There I see the data for PMD Rest GFT and Papier.

**Comment by Johnwulp** [comment]
Issue has been fixed (hopefully) with a new version. See commit https://github.com/Johnwulp/rad-afval/commit/079d067d15c382fbfab5e5a5504c8fcba1e0f90f for details. 
If you use HACS there is an update that can be installed, otherwise just replace the files manually
