### ISSUE TITLE
Version in manifest-files

### ISSUE THREAD

**Issue by llevering** [Johnwulp/rad-afval#2]
From the log of Home Assistant:
`No 'version' key in the manifest file for custom integration 'rad-afval'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'rad-afval'.`

They want a version key in the manifest file, so if in the future with a specific add-on an security issue is found that it can be blocked.

Thanks for the integration btw really useful!

**Comment by Johnwulp** [comment]
Hi, Thanks for reporting this. It's fixed 05f7f17f59eeb2e16097500b3d9ac4c47d3e3c7b
