### ISSUE TITLE
vraagje

### ISSUE THREAD

**Issue by CorKevenaar** [Johnwulp/rad-afval#3]
He John
hoe lastig is dit om aan te passen naar die van mijn woonplaats Doetinchem

ze gebruiken daar mijn afvalwijzer
https://www.mijnafvalwijzer.nl/nl/7006HT/162/

is dat lastig om te integreren  (ben net pas gestart met HA)

**Comment by Johnwulp** [comment]
Hallo @CorKevenaar, 

Het aanpassen van deze plugin naar mijnafvalwijzer is helaas niet mogelijk omdat de gemeente hoekschewaard niet in de afvalwijzer staat. Dit is juist de reden dat ik deze plugin heb gemaakt ;-) Andersom is bij radbv.nl geen informatie voor jouw gemeente beschikbaar.

Groet, John

**Comment by CorKevenaar** [comment]
Ok dank je voor het snelle antwoord

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________
