### ISSUE TITLE
Vandaag

### ISSUE THREAD

**Issue by Visje31** [Johnwulp/rad-afval#4]
Hoi John,

Ik zit te kijken in HA en daar staat dat het plastic afvel op 25 aug. opgehaald wordt.
In feite wordt het vandaag de 18de opgehaald, maar nu lijkt het een week later te zijn.
Kan je de datum van het item (dus plastic, rest, groen, papier) op vandaag (of de datum van vandaag) zetten?
Als ik namelijk 's morgens kijk, in Strien zijn ze niet zo snel, dan mis ik de ophaaldag, omdat ik dan denk dat het een of twee weken later zou zijn.

**Comment by Johnwulp** [comment]
Hi.

er zit inderdaad geen sensor in van vandaag. Ik zal kijken of ik deze kan toevoegen.

**Comment by Visje31** [comment]
Thanks,

Dan is het op de dag van ophalen nog duidelijk welke er aan de beurt is.
Toppie!

**Comment by Johnwulp** [comment]
Ik heb een nieuwe update klaargezet. Hiermee is wordt het mogelijk om te zien wat er vandaag wordt opgehaald. De waarde van de sensor next_pickup_in_days is dan 0.

**Comment by Visje31** [comment]
Dank je wel!
