### ISSUE TITLE
Too many integrations?

### ISSUE THREAD

**Issue by AJediIAm** [Johnwulp/rad-afval#7]
I noticed that there are 5 HACS integrations for dutch and belgium garbage collection. Wouldn't it be better to combine the efforts into one or two integrations?

this integration seems to be very specific and rarely used. Does it still work?
Are there any significant benefits of this integration over the afvalbeheer and afvalwijzer?

**Comment by Johnwulp** [comment]
This integration was created in 2020 before others supported our region. It still works, you don’t have to use it if another integration suits your needs.

**Comment by AJediIAm** [comment]
I was a bit overweldigend by the amount of options in the new HACS experimental view, so I thought to see is a bit of cleaning up would be in order to make it easier for other users to find what they need and possibly consolidate development efforts to improve the quality of one or two integrations.

If no further development is done on this integration, it could be removed from HACS while still allowing existing users to continue to use it. Its your call however.

**Comment by Visje31** [comment]
Why would this integration be terminated? There are more people that do use it. 
So because you have found a couple more, they have to change which integration they use? 
That's a bit "het paard achter de wagen spannen"

**Comment by AJediIAm** [comment]
Terminating the HACS integration will not remove it from instances which currently use it. It allows new users to see the trees through the forest and joining development efforts on one instead of 5 integrations might improve the overall quality and user experience.

Home Assistant core is constantly merging functionality in a single consistent user experience. Once in a while, I come across integrations which appear to do the same thing. Sometimes, the authors are not aware of it. Bringing up the topic has resulted in projects succesfully merging their repositories and features into a single better integration.

Again, no need to feel any pressure. Its just a suggestion and its your goal. Every Home Assistant and integration developer is a hero in my book, including you. Keep doing what you do <3
